- name: Install bird2
  apt:
    name:
      - bird2

- name: Deploy BIRD config
  template:
    src: bird.conf
    dest: /etc/bird/bird.conf
    mode: "640"
    owner: root
    group: bird
  notify:
    - Reload bird
