- name: Install conntrackd
  apt:
    name:
      - conntrack
      - conntrackd
    state: present

- name: Deploy conntrackd config
  template:
    src: conntrackd.conf
    dest: /etc/conntrackd/conntrackd.conf
    mode: "644"
  notify:
    - Restart conntrackd
