- name: Deploy systemd-network config
  template:
    src: networkd/{{ item }}
    dest: /etc/systemd/network/{{ item }}
    mode: "644"
  loop:
    - mgmt.network
    - dmz.network
    - uplink.network
    - sown.network
    - oob.network
    - oob.netdev
  notify:
    - Reload networkd
