- name: Setup sysctls
  include_tasks: sysctl.yml

- name: Setup firewall
  include_tasks: firewall.yml

- name: Setup bird
  include_tasks: bird.yml

- name: Setup conntrack
  include_tasks: conntrack.yml

- name: Setup keepalived
  include_tasks: keepalived.yml

- name: Setup interfaces
  include_tasks: interfaces.yml
