- name: Install packages
  apt:
    name:
      - git
    state: present

- name: Make /opt/sown
  file:
    state: directory
    dest: /opt/sown
    mode: "755"

- name: Clone network config
  git:
    repo: git@github.com:sown/network.git
    dest: /opt/sown/network
    update: false  # noqa: latest

- name: Setup sysctls
  include_tasks: sysctl.yml

- name: Setup firewall
  include_tasks: firewall.yml

- name: Setup bird
  include_tasks: bird.yml

- name: Setup conntrack
  include_tasks: conntrack.yml

- name: Setup interfaces
  include_tasks: interfaces.yml
