# The playbook.
# It will take a while to run all of this
# You can restrict how much you run using tags.

- hosts: all

- hosts: all
  roles:
    - sown-common
    - monitored
    - {role: unattended-upgrades, tags: unattended-upgrades}
  tags: common
- hosts: all
  roles:
    - cron-mail-redirect
  tags: cron-mail-redirect
- hosts: device_roles_Router
  roles:
    - pxe
  tags: pxe
- hosts: device_roles_Router
  roles:
    - dns-slave
  tags: dns-slave
