# The playbook.
# It will take a while to run all of this
# You can restrict how much you run using tags.

- hosts: all

- hosts: all
  roles:
    - role: sown_common
      tags: sown_common
    - role: monitored
      tags: monitored
    - role: unattended_upgrades
      tags: unattended_upgrades
    - role: cron_mail_redirect
      tags: cron_mail_redirect
  tags: common
- hosts: device_roles_Router
  roles:
    - role: pxe
      tags: pxe
    - role: dns_slave
      tags: dns_slave
- hosts: tags_Backup
  roles:
    - backed_up
  tags: backed_up
