# The playbook.
# It will take a while to run all of this
# You can restrict how much you run using tags.

- hosts: all

- hosts: all
  roles:
    - role: sown_common
      tags: sown_common
    - role: monitored
      tags: monitored
    - role: unattended_upgrades
      tags: unattended_upgrades
    - role: cron_mail_redirect
      tags: cron_mail_redirect
  tags: common
- hosts: device_roles_router
  roles:
    - role: pxe
      tags: pxe
    - role: dns_slave
      tags: dns_slave
# temp, will be routers once we're done
- hosts: GW-B32
  roles:
    - role: gw
      tags: gw
- hosts: tags_backup
  roles:
    - backed_up
  tags: backed_up
- hosts: device_roles_ssh-gateway
  roles:
    - role: ssh_gateway
      tags: ssh_gateway
