version: 2
workflows:
  version: 2
  test:
    jobs:
      - lint
jobs:
  lint:
    docker:
      - image: sown/ansible-lint
    steps:
      - checkout
      - run:
          name: Run YAMLlint
          command: yamllint .
      - run:
          name: Run ansible-lint
          command: ansible-lint playbook.yml
