- import_tasks: nrpe-install.yml
  tags: nrpe
- name: fetch host details
  tags: nrpe_psu
  setup:
- import_tasks: psu.yml
  tags: nrpe_psu
  when:
    - "ansible_facts['virtualization_role'] in ('NA', 'host')"  # physical machines
    - "psu_monitoring|default(true)"  # we allow opting out of this eg for single psu machines
