- name: "Add backup scripts dir"
  file:
    path: /etc/backup-scripts
    state: directory
- name: "Add backup files dir"
  file:
    path: /var/lib/backup
    state: directory
    mode: "700"
- name: "Add backup3 key"
  authorized_key:
    user: root
    state: present
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDUTbn+rkSv3vSj+T4MOBgLmrW8WPdUyDsV+mjdeKo7OjYXI91TT3bO+nPNl4hdBXhKVVTaylmEn7YW9QGpaqpWpZd2JonBd3FHWcu/vcS1rshqA8XkxeuJSY1QvMNA4THuN9lkgiT+tsIlfp25LSBfhWrHDDuC6geaC2ic3pbjrTw0/8U2AYXyKtEF8CMn7X/IlMBiO8SfUNZUftx+bSGm41wdRKPzAbeBQy6ojtuyinA0QTVyeHw+m1DoN2EQTFkTBnlp3mS1Z4PWs0rXBXYF+p4lJlWCVN8QuunQFRR+duanSgda1vxXfq6KIw1alZio+z8taSupCOO5arxI9Ux root@backup3"
    key_options: 'from="10.5.0.247,2001:630:d0:f700::247"'
