- name: Checkout ferry-api into /opt/ferry
  git:
    repo: https://github.com/trickeydan/ferry-api.git
    dest: /opt/ferry-api
    version: 3a33e8df5989f797f6202e1145e5072f22f738ae
  notify: Restart ferry-service

- name: Install compose file
  template:
    src: files/docker-compose.override.yml
    dest: /opt/ferry-api/docker-compose.override.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
  notify: Restart ferry-service
