# Install Utilities to Host
- name: Install utility packages
  apt:
    name:
      - curl
      - dnsutils
      - git
      - sl
      - strace
      - tmux
      - vim
    state: present
  become: true
