# Tasks that are common to all hosts
# For Ubuntu and Debian Hosts only.

- name: Configure utilities
  import_tasks: install-utilities.yml
  tags: utilities
- name: Configure motd
  import_tasks: motd.yml
  tags: motd
- name: Configure auth
  import_tasks: ssh-auth.yml
  tags: ssh_gateway_auth
