---
- name: Add ssh gateway keys
  ansible.posix.authorized_key:
    user: root
    state: "{{ item.state | default('present') }}"
    key: "{{ lookup('file', item.key) }}"
  with_items:
    - key: sown-login.pub
    - key: sown-login2.pub
    - key: sown-auth2.pub
      state: absent
  when: add_ssh_gateway_keys is undefined or add_ssh_gateway_keys
