---
- name: Install git
  ansible.builtin.apt:
    name: git
    state: present

- name: Checkout container configuration
  ansible.builtin.git:
    repo: "git@github.com:sown/containers-dev-docker-config.git"
    dest: "/docker/managed"
    version: master

- name: Setup containers
  community.docker.docker_compose_v2:
    project_src: "{{ item }}"
  with_items:
    # setup utility containers first
    - "/docker/managed/traefik"
    # setup remaining containers
