- name: Checkout kmibot into /opt/kmibot
  git:
    repo: https://github.com/sown/kmibot.git
    dest: /opt/kmibot
    version: c288f25f8224452ecc2641a74bb79177597e53e3
  notify: Restart KMIBot

- name: Install extra config
  template:
    src: files/config.toml
    dest: /opt/kmibot/config.toml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
  notify: Restart KMIBot
