- name: Checkout kmibot into /opt/kmibot
  git:
    repo: https://github.com/sown/kmibot.git
    dest: /opt/kmibot
    version: dbbfcb651a129cb240f319da09c6a0b7260ba7a6
  notify: Restart KMIBot

- name: Install extra config
  template:
    src: files/config.toml
    dest: /opt/kmibot/config.toml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
  notify: Restart KMIBot
