- name: Create install directory
  file:
    path: /usr/local/bin/
    state: directory

- name: Install compose-switch
  get_url:
    url: "{{ docker_compose_url }}"
    dest: /usr/local/bin/docker-compose
    mode: "0755"

- name: Install python3-requests for ansible.community.docker
  package:
    name:
      - python3-requests
    state: present

- name: Create docker group
  group:
    name: "{{ docker_user.name }}"
    state: present
    gid: "{{ docker_user.id }}"

- name: Create docker user
  user:
    name: "{{ docker_user.name }}"
    uid: "{{ docker_user.id }}"
    group: "{{ docker_user.name }}"
    create_home: false

- name: Clean up docker containers
  cron:
    name: clean up docker containers
    hour: 1
    minute: 0
    job: docker system prune -af --volumes
    cron_file: docker_cleanup
    user: root
