---
- name: Install python3 pip
  apt:
    name: python3-pip
    state: present

# Install docker-compose as required by ansible
# Ansible requires docker-compose version 1 insalled by python
# dockers python library v 7 breaks compatibility with docker-compse with no intention to fix either version
# so lock the version of docker as well
- name: Install docker-compose
  pip:
    name:
      - docker==6.1.3
      - docker-compose
    state: present
