- name: Install bind
  apt:
    name: bind9

- name: Deploy /etc/bind/named.conf.options
  file:
    src: named.conf.options
    dest: /etc/bind/named.conf.options
    mode: "644"
  notify:
    - Reload bind

- name: Deploy /etc/bind/named.conf.local
  copy:
    src: files/named.conf.local
    dest: /etc/bind/named.conf.local
    mode: "644"
  notify:
    - Reload bind
