# Add the SOWN MOTD
- name: Install Common Packages for MOTD
  apt:
    name:
      - libpam-modules
      - base-files
    state: present
  become: true

- name: Install Ubuntu-specific Packages for MOTD
  apt:
    name:
      - ubuntu-release-upgrader-core
      - update-notifier-common
    state: present
  become: true
  when:
    - ansible_facts['distribution'] == "Ubuntu"

- name: Generate figlet for /etc/motd
  delegate_to: localhost
  shell: >
    echo "Welcome to\n$(figlet -f /usr/share/figlet/smslant.flf
    {{ motd_org_name|default('SOWN') }}
    {{ ansible_hostname|replace('sown-', '')|replace('suws-', '') }})"

  register: motd
  changed_when: false
  check_mode: false

- name: Deploy /etc/motd
  copy:
    content: "{{ motd.stdout }}"
    dest: "/etc/motd"
  become: true

# Remove old files

- name: Remove deprecated MOTD files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/motd.tail"
    - "/etc/update-motd.d/99-footer"
    - "/etc/update-motd.d/99-header"
    - "/etc/update-motd.d/09-sown-machinename"
  become: true
